chore: Update .env.sample & add a check for google oauth client id (#223)

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -40,6 +40,15 @@ jobs:
         steps:
             - uses: actions/checkout@v2
 
+            - name: Check if necessary ENV variables are set
+              run: |
+                  if [ -z "$VITE_OAUTH_ID_GOOGLE" ]; then
+                    echo "ERROR: missing google oauth client id"
+                    exit 1
+                  fi
+              env:
+                  VITE_OAUTH_ID_GOOGLE: ${{ secrets.PROD__REACT_APP_OAUTH_ID_GOOGLE }}
+
             - name: Set tag ENV
               run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
